-- ContextIQ demo pipeline schema
-- NOTE: This migration intentionally does not add auth FKs or RLS policies.
-- It is designed for a demo-only environment.

create table if not exists public.daily_summaries (
  id bigint generated by default as identity primary key,
  activity_date date not null,
  source_window_start timestamptz not null,
  source_window_end timestamptz not null,
  total_minutes integer not null default 0,
  category_minutes jsonb not null default '{}'::jsonb,
  location_minutes jsonb not null default '{}'::jsonb,
  switch_count integer not null default 0,
  longest_session_minutes integer not null default 0,
  tod_morning_minutes integer not null default 0,
  tod_afternoon_minutes integer not null default 0,
  tod_evening_minutes integer not null default 0,
  tod_night_minutes integer not null default 0,
  productive_minutes integer not null default 0,
  productive_ratio numeric(6,4) not null default 0,
  source_log_count integer not null default 0,
  created_at timestamptz not null default now()
);

create unique index if not exists daily_summaries_activity_date_key
  on public.daily_summaries(activity_date);

create table if not exists public.pattern_findings (
  id bigint generated by default as identity primary key,
  daily_summary_id bigint not null references public.daily_summaries(id) on delete cascade,
  pattern_type text not null check (pattern_type in ('routine', 'study_block', 'distraction', 'drop_off', 'none')),
  prediction_probability numeric(6,4) not null check (prediction_probability >= 0 and prediction_probability <= 1),
  confidence_score text not null check (confidence_score in ('low', 'medium', 'high')),
  model_version text not null,
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create unique index if not exists pattern_findings_summary_model_key
  on public.pattern_findings(daily_summary_id, model_version);

create index if not exists pattern_findings_created_at_idx
  on public.pattern_findings(created_at desc);

create table if not exists public.suggestions (
  id bigint generated by default as identity primary key,
  pattern_finding_id bigint not null unique references public.pattern_findings(id) on delete cascade,
  suggestion_text text not null,
  explanation text not null,
  limitation text not null,
  confidence_score text not null check (confidence_score in ('low', 'medium', 'high')),
  llm_model text not null,
  prompt_version text not null,
  raw_response jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists suggestions_created_at_idx
  on public.suggestions(created_at desc);
